version: "3.7"
services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: scaperapp
        container_name: app-php
        restart: always
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - database
        links:
            - database
        networks:
            - app-network
        ports:
            - '5173:5173'
        env_file:
            - ./app/.env

    nginx:
        image: nginx:alpine
        container_name: app-nginx
        restart: always
        ports:
            - "${NGINX_PORT:-8080}:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - app-network
        depends_on:
            - database
        env_file:
            - ./app/.env
            
    database:
        image: mysql:5.7
        container_name: app-database
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-appcake}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root123}
            MYSQL_PASSWORD: ${DB_PASSWORD:-root123}
            MYSQL_USER: ${DB_USERNAME:-appcake}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network
        volumes:
            - ./docker/data/mysql:/var/lib/mysql

    sqlite:
        image: nouchka/sqlite3:latest
        container_name: app-sqlite
        stdin_open: true
        tty: true
        volumes:
            - ./docker/data/sqlite:/root/db/

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: app-phpmyadmin
        restart: unless-stopped
        tty: true
        depends_on:
            - database
        ports:
            - "${PMA_PORT:-9090}:80"
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME:-appcake}
            PMA_PASSWORD: ${DB_PASSWORD:-root123}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root123}
            UPLOAD_LIMIT: 2048M
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - ${RABBITMQ_AMQP_PORT:-5672}:5672
            - ${RABBITMQ_HTTP_PORT:-15672}:15672
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-root}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-pass}
        volumes:
            - ./docker/data/rabbitmq/data/:/var/lib/rabbitmq/
            - ./docker/data/rabbitmq/log/:/var/log/rabbitmq
        command: ["bash", "-c", "chmod 600 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
